### ISSUE TITLE
Cannot find *.vue files

### ISSUE THREAD

**Issue by crystalfp** [Gerrit0/typedoc-plugin-vue#2]
I don't know if it is a problem of typedoc or of this plugin, so please take a look at https://github.com/microsoft/tsdoc/issues/435 .
No problem to generate documentation for *.ts files, but tsdoc cannot find *.vue files.
What I'm doing wrong?
Thanks for your help!
mario

**Comment by Gerrit0** [comment]
TypeDoc does not support .vue files. It only supports projects which `tsc` can be run on.

**Comment by crystalfp** [comment]
My mistake. The limited documentation on the plugin sent me on the wrong path.
